### ISSUE TITLE
Making API Calls

### ISSUE THREAD

**Issue by ska-ibees** [GlodoUK/helm-charts#12]
Hello again,

Belated Happy New Year!

Well, i am unable to make any outbound call to any external endpoint. 

`e.g. requests.post(url)`

Wanted to check if any specific config is required to make it work?

Thank you!

**Comment by theangryangel** [comment]
Happy new year Syed, I'm afraid there's nothing in the helm chart to implement network policies, etc. to restrict outbound access. We've got a number of installations using the Odoo chart making outbound API calls to things like MSTeams, Magento installations, carrier APIs, etc. 

`ndots` and timeouts is something we've contented with on third party clusters where there were a large number of DNS suffixes. A quick test would be to try to add a trailing dot to the name to see if it helps?

**Comment by ska-ibees** [comment]
Thanks dear. As of now I am making calls to external thirdparty endpoints (Outside cluster). Same calls are okay within my local dev machines (Doodba on Docker). Thought something is there in the image itself that is making it isolated in the K8s. Anyways, let me check it further... Thanks again!
