### ISSUE TITLE
 Multiprocessing vs Multithreading

### ISSUE THREAD

**Issue by ska-ibees** [GlodoUK/helm-charts#14]
Hello again,

Opening this discussion here regarding  Multiprocessing vs Multithreading for Odoo in K8s.

Do you see any benifits of setting workers = <0 or is it better to keep workers = 0 and increase replica count?

**Comment by theangryangel** [comment]
We’ve done some experimentation, and currently our thinking is it depends on the size and scale of the installation.

Our smallest deployments tend to be 1 replica running everything (cron, web and longpolling), usually with workers = 6. This gives us the convenience of kube, and a relatively simple deployment, and it’s usually enough workers to deal with some of the burst-y user interactions from. On our smaller installs we could probably use less fewer workers.

For larger more complex installations we tend to split things out: 

- job queue and cron living on it’s own replica
- 2 or more web replicas with workers = 6
- and optionally longpolling (Odoo gevent) on another (I have mixed feelings about whether this step is worthwhile)

There are a few problems with these lareger installations that need to be taken into consideration:

- for upgrades we’ve found its best to scale down the job queue, cron and longpolling replicas to 0, web to 1 and then push out an update. Currently the helm chart doesn’t do this for you and it’s on my mental roadmap, but we’ve just not got to it yet. We need this to simplify some of our deployments but it’s just not high enough on my TODOs yet
- for multiple replicas you either need ReadWriteMany storage or you need to look at alternatives, like camptocamp’s attachment modules (https://github.com/camptocamp/odoo-cloud-platform). Currently for simplicity we using NFS, but practically that’s got it’s own issues.
- redis or memcache for session storage is almost mandatory

**Comment by ska-ibees** [comment]
Thanks for sharing insightful info. 

I have almost same feeling about the topic. 

Atleast workers = 6  seems to be a good starting point. 

> * and optionally longpolling (Odoo gevent) on another (I have mixed feelings about whether this step is worthwhile)

Well, I am not sure how to implement it using the chart as it seems to be handled by the web replica itself. But what we are experiencing is a delay of few seconds for one of the database. I am not sure as why only one database is showing such behavior  inspite that whole implementation is same for all. I think it is worth trying to seperate longpolling. 



> * for upgrades we’ve found its best to scale down the job queue, cron and longpolling replicas to 0, web to 1 and then push out an update. Currently the helm chart doesn’t do this for you and it’s on my mental roadmap, but we’ve just not got to it yet. We need this to simplify some of our deployments but it’s just not high enough on my TODOs yet

Interesting... as what I am doing is to manually pausing all schedule tasks like Email fetch etc... before pushing upgrades. I was hesitant to deploy job queue and cron on different replicas as I am having multi DB/Multi domains setup. 



> * for multiple replicas you either need ReadWriteMany storage or you need to look at alternatives, like camptocamp’s attachment modules (https://github.com/camptocamp/odoo-cloud-platform). Currently for simplicity we using NFS, but practically that’s got it’s own issues.

True!
Well, I am on AWS EKS and using EFS storage. So far I don't see any issues with it. 



> Despite the negatives I feel it is worth running replicas > 1 on busy installations. But be aware the chart needs some further work :)

Agreed, running replicas > 1 is important for HA and load distribution.

**Comment by theangryangel** [comment]
> Well, I am not sure how to implement it using the chart as it seems to be handled by the web replica itself. But what we are experiencing is a delay of few seconds for one of the database. I am not sure as why only one database is showing such behavior inspite that whole implementation is same for all. I think it is worth trying to seperate longpolling.

Right now the chart doesnt support it directly. What we’ve done on the instances so far is use helm template to render and then modify. It’s not currently in the chart yet as I’m not 100% sure it’s worth it. You can do it by basically taking the web deployment, and modifying it so that the args are odoo gevent, and then set the longpolling ingress to point at that directly, rather than the web instances. I can setup a small PR to add it, if it would help?

> Interesting... as what I am doing is to manually pausing all schedule tasks like Email fetch etc... before pushing upgrades. I was hesitant to deploy job queue and cron on different replicas as I am having multi DB/Multi domains setup.

This shouldn’t really matter about being separate imho. I will admit we don’t use multi-DB, but do we use multi-domain, and multi-company.

We tend to run job queue separately because we often need very different memory limits, timeouts, etc. plus on the odd occasion where we do need to stop the job queue, we can without taking down the web ui at all.

**Comment by ska-ibees** [comment]
> Right now the chart doesnt support it directly. What we’ve done on the instances so far is use helm template to render and then modify. It’s not currently in the chart yet as I’m not 100% sure it’s worth it. You can do it by basically taking the web deployment, and modifying it so that the args are odoo gevent, and then set the longpolling ingress to point at that directly, rather than the web instances. I can setup a small PR to add it, if it would help?

Got your point. So, basically it is like replicating web part and pointing ingress to it only with longpolling port. I will give it a try. Yes, it would be great to see in the PR. 



> This shouldn’t really matter about being separate imho. I will admit we don’t use multi-DB, but do we use multi-domain, and multi-company.
> 
> We tend to run job queue separately because we often need very different memory limits, timeouts, etc. plus on the odd occasion where we do need to stop the job queue, we can without taking down the web ui at all.

Well, previously i tried implementing it. However, couldn't successed, mainly coz of lack of config level knowledge to setup Job Queue. :)
