### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ska-ibees** [GlodoUK/helm-charts#4]
Hi there,

Thanks for sharing this chart. This is similar to what I have been working on for a private project. Few questions to ask plz:

1. Is it based on Vanilla doodba? If not then is the image's code open source?
2. Have you tested job_queue with a session pooler e.g. pg_bouncer?

**Comment by theangryangel** [comment]
Hi Syed, welcome :)

1. Yes, but it's a bring-your-own-image - we don't provide any. For us each deployed chart usually uses a unique image (each project we do tends to have at least some custom code).
2. For our job queue instances we bypass pgbouncer and connect directly to the DB server at the moment (using the special config options https://github.com/OCA/queue/blob/35fbf961d537082d50e794917c5a6b1dcb7038af/queue_job/jobrunner/runner.py#L187-L198).

**Comment by ska-ibees** [comment]
Thanks for the quick response.

So, as expected each image should be unique. I just wanted to know if you
have done anything within the image to make it compatible with the helm
chart. For example, any changes done for the queue_job to work etc.

Bypassing pgbouncer for job queue instances is a brilliant approach. I
would definitely try this out. I may need some extra tweaks as I am using
single Odoo instance for multiple domains and each domain is having a
specific dB (using dB_header module). Wish me a luck 😅

**Comment by theangryangel** [comment]
>  I may need some extra tweaks as I am using single Odoo instance for multiple domains and each domain is having a specific dB (using dB_header module). Wish me a luck 

You should be able to do most of your custom config using the config snippets options (https://github.com/GlodoUK/helm-charts/blob/master/odoo/templates/configmap.yaml#L21-L25).

For the ingress you'd definitely need to do something custom thought. We're happy to take PRs if it adds extra functionality :)

Good luck!

**Comment by ska-ibees** [comment]
> You should be able to do most of your custom config using the config snippets options (https://github.com/GlodoUK/helm-charts/blob/master/odoo/templates/configmap.yaml#L21-L25).

Yea for the implementation of multi-domain, multi DB and pgbouncer will definitely need to have custom configs.

> For the ingress you'd definitely need to do something custom thought. We're happy to take PRs if it adds extra functionality :)

As of now using Nginx (for the sake of adding custom proxy headers proxy_set_header for the domain and DB mapping and also need to use a single application load balancer). Not sure how to achieve it using traefik.
