### ISSUE TITLE
 accessMode: ReadWriteMany

### ISSUE THREAD

**Issue by ska-ibees** [GlodoUK/helm-charts#42]
Hi Again,

Good to see the continued development of this chart. 

Well, regarding the [accessMode: ReadWriteMany](https://github.com/GlodoUK/helm-charts/blob/8909fa38cc838ae3f3aac8b487ebccd578f519f1/charts/odoo/values.yaml#L65), there is no issue with the file system like AWS EFS. However, such a thing is missing in other cloud providers. 

So, could you please comment on which option is better among the below:

1. Using NFS deployed on same K8s cluster
2. Using a S3 compatible storage

Or any other suggestions in this regard?

Many thanks!

**Comment by theangryangel** [comment]
> Using NFS deployed on same K8s cluster

We've had mixed experiences with this. I tried out running NFS inside k8s on OVH and it was awful performance, but we didn't spend a lot of time trying to figure out why.

On an on-premises cluster, it was fine.

Ultimately at the end of the day, you will have NFS issues (locking, etc.), so it just needs to be setup right.

> Using a S3 compatible storage

S3 or S3 compatible storage needs to be close and fast for a lot of Odoo's needs. It works, but the further away and slower the worse it gets.

One idea we've had, but not tried yet is to run Minio in-cluster.

The other way is to put some attachments in S3 and some in the DB. 

Camptocamp have several modules to help with this https://github.com/camptocamp/odoo-cloud-platform/tree/16.0/attachment_s3 which uses https://github.com/camptocamp/odoo-cloud-platform/tree/16.0/base_attachment_object_storage underneath the hood which allows you to follow this half and half pattern

That said, the best performance we've had is with providers with good RWX performance (Azure, AWS, on-prem).

**Comment by ska-ibees** [comment]
Thanks for the detailed response. 

I had similar feelings for NFS & S3 compatible storage. 

Don't know much about Minio. However, going to give [Longhorn](https://longhorn.io/) a try. 

As a last resort will follow camptocamp's approach. 

Thanks again!

**Comment by theangryangel** [comment]
Please do follow up with how you get on with Longhorn :) I've not tried it out, and I've heard both good and bad things

**Comment by ska-ibees** [comment]
Sure, will update the progress here.

As of now, I am trying Linode and it seems that the default image(Alpine) kernel with their managed k8s cluster i.e. LKE doesn't support nfs/iscsi ;)

As per their support, it can be deployed with unmanaged K8s like Rancher... which I would like to avoid for obvious reasons.

Looking for a setup with minimal management/maintenance overhead.
