### ISSUE TITLE
I have a really quick question: Why are we not using click-odoo-backupdb instead of pgdump?

### ISSUE THREAD

**Issue by hasnain-byte** [GlodoUK/helm-charts#56]

**Comment by theangryangel** [comment]
> Usage: click-odoo-backupdb [OPTIONS] DBNAME DEST
>   Create an Odoo database backup.
>   This script dumps the database using pg_dump. It also copies the filestore.

The last part is the important part for us. We have filestores in excess of hundreds of GB, and found that we needed/wanted differential backups to get the backups done in a reasonable timeframe. `click-odoo-backupdb` at the time did not support this, so we opted to use Velero with restic.

**Comment by theangryangel** [comment]
To just expand on the above, we do 2 different types of backups on our production installs:
1. Snapshots of filestore and database using pg_dump and Velero (restic)
2. Continuous backups of PostgreSQL using WAL archiving and base backups
