### ISSUE TITLE
Mixing sessions of different users

### ISSUE THREAD

**Issue by ska-ibees** [GlodoUK/helm-charts#7]
After passing a long journey of K8s implementation and Odoo development. Last night we actually started testing our new setup. There were total four users that were loged in. However, what we experienced was something un-expected. 

Each one of user was switching with one another without any relogin attempt.

Like with every browser refresh there was a different user with all rights and access. 

May I know how are you handling sessions in your deployments?

**Comment by theangryangel** [comment]
Small instances with single replicas we just use the default werkzeug sessions.

For multiple replicas we use redis session storage for performance. 

We have used default werkzeug sessions for multiple replicas, with shared storage, but on higher traffic installs there’s a definite performance impact as each replica locks the session file

Never have we seen your behaviour…

**Comment by ska-ibees** [comment]
Thanks for the insightful response. 

Yes, such behavior is never observed and it is totally unexpected and troublesome. There must be some really weired thing going on here. 

I think it's time to go with redis. Could you please recommend any existing Odoo module for redis implementation?

**Comment by ska-ibees** [comment]
Thanks for the links. 

BTW issue of mixing user sessions has been resolved.  It was caused by [simple cache ](https://github.com/traefik/plugin-simplecache)middlewear in Traefik. I was hoping to get some performance benifts but infact it was caching everything thus messing up CSRF tokens.
